name: Run Tests

on:
  push:
    branches:
      - masterBE
  pull_request:
    branches:
      - masterBE

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'corretto'  # Mueve distribution debajo de java-version
          cache: 'maven'            # Asegúrate de que 'maven' esté entre comillas

      - name: Build with Maven
        run: mvn clean install

      - name: Run tests
        run: mvn test

